<?php

echo"<div class='contenier' id='Main'>
    <li>Lançamento eua: 05/10/1995 </li>
    <li>Lançamento Brasil em: novembro de 1995</li>
    <li>Lançamento Europa: dezembro 1995</li>
    <p>A história começa com a cegonha levando dois bebês gêmeos para seus pais, porém ele é atacado por Kamek, que sequestra um dos bebês e o outro cai no mar. Kamek fica furioso pois só tem um bebe em vez de dois e manda seus lacaios atras do outro.</p>
    <p>O outro bebe cai em direção a ilha dos yoshis, caindo na costas de um deles. o Yoshi mão sabe ler então resolvem ir em direcao ao bilhete( castelo do Bowser).</p>
</div>";


?>